# Generated by Django 2.2.4 on 2019-08-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255)),
                ('label', models.SlugField(max_length=255, unique=True)),
                ('help', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255)),
                ('label', models.SlugField(max_length=255, unique=True)),
                ('info', models.TextField()),
                ('max_impact', models.DecimalField(decimal_places=3, max_digits=10)),
                ('question', models.TextField()),
            ],
        ),
    ]
