# Generated by Django 2.2.4 on 2019-08-24 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suffi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['max_impact']},
        ),
        migrations.AddField(
            model_name='challenge',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='suffi.Category'),
            preserve_default=False,
        ),
    ]
