# Generated by Django 2.2.4 on 2019-08-24 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suffi', '0004_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='challenge',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='suffi.Challenge'),
            preserve_default=False,
        ),
    ]
