# Generated by Django 2.2.4 on 2019-08-24 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suffi', '0005_option_challenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='suffi.Challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activeChallenges', to=settings.AUTH_USER_MODEL)),
                ('valueGoal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='suffi.Option')),
                ('valueStart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='suffi.Option')),
            ],
        ),
    ]
