# Generated by Django 2.2.4 on 2019-08-24 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suffi', '0008_remove_activechallenge_valuegoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activechallenge',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suffi.Challenge'),
        ),
        migrations.AlterField(
            model_name='activechallenge',
            name='valueStart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suffi.Option'),
        ),
    ]
