# Generated by Django 2.2.4 on 2019-08-24 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suffi', '0009_auto_20190824_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='activechallenge',
            name='valueGoal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='activeChallenges_Goal', to='suffi.Option'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activechallenge',
            name='valueStart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activeChallenges_Start', to='suffi.Option'),
        ),
    ]
