# Generated by Django 2.2.4 on 2019-08-24 19:19

from django.db import migrations
from suffi.greenAPI.models import Category, Challenge, Option
import pandas as pd

def init_data(apps, schema_editor):
    # init Category table
    PATH = "data/initData.csv"
    df = pd.read_csv(PATH)

    cat_labels = ["Lebensmittel", "Verkehr", "Wohnen", "Kleder und Schuhe"]
    cat_icons = ["utensils", "car", "home", "tshirt"]
    for cat_label, cat_icon in zip(cat_labels, cat_icons):
        help = "Very useful information about" + cat_label
        cat = Category(icon=cat_icon, label=cat_label, help=help)
        cat.save()
        # init Challange table
        for idx, row in df.loc[df.category==cat_label].drop_duplicates('label').iterrows():
            info = "The " + row.label + " challange is a very good challange!"
            challange = Challenge(icon=row.icon,
                                  label=row.label,
                                  info=info,
                                  max_impact=row.max_impact,
                                  question=row.question,
                                  category=cat)
            challange.save()
            if not pd.isnull(row.option_title):
                for idx, option_row in df.loc[df.label==row.label].iterrows():
                    option = Option(title=option_row.option_title, co2=option_row.option_co2, challenge=challange)
                    option.save()

    # # init Challange table
    # chllg_labels = ["Lokal und Regional einkaufen",
    #                 "Milchprodukte",
    #                 "Eier",
    #                 "Fleisch und Fisch",
    #                 "Label Produkte",
    #                 "Lebensmittel Wegwerfen",
    #                 "Autofahren oder Motorradfahren",
    #                 "Flugzeugreisen pro Jahr",
    #                 "Heizung",
    #                 "Ökostrom",
    #                 "Kleider und Schuhe"]
    # chllg_category = ["Lebensmittel",
    #                   "Lebensmittel",
    #                   "Lebensmittel",
    #                   "Lebensmittel",
    #                   "Lebensmittel",
    #                   "Lebensmittel",
    #                   "Verkehr",
    #                   "Verkehr",
    #                   "Wohnen",
    #                   "Wohnen",
    #                   "KlederundSchuhe"]
    # chllg_question = ["Wie viel saisonales Obst und Gemüse kaufen Sie ein?",
    #                 "Wie oft konsumieren Sie Milch und Milchprodukte?",
    #                 "Wie oft essen Sie Eier?",
    #                 "Wie oft essen Sie Gerichte, die Fleisch oder Fisch enthalten?",
    #                 "Welchen Anteil haben Label-Produkte (Bio, MSC, Fair Trade) an Ihrem Einkauf?",
    #                 "Wie häufig werfen Sie Lebensmittel weg?",
    #                 "Wie viele Kilometer legen Sie jährlich per Auto oder Motorrad ausserhalb der Arbeitszeit, lenkend oder als Fahrgast zurück? ",
    #                 "Wie viele Stunden sind Sie in den letzten fünf Jahre durchschnittlich mit dem Flugzeug privat gereist?",
    #                 "Womit wird Ihr Zuhause im Winter hauptsächlich beheizt?",
    #                 "Welchen Anteil hat Ökostrom mit dem Label «naturemade star» in Ihrem Haushalt?",
    #                 "Wieviel geben Sie monatlich für Kleider und Schuhe aus?"]
    # chllg_maxImpact = [0.55,
    #                    1.71,
    #                    0.12,
    #                    1.42,
    #                    0.63,
    #                    1.6,
    #                    5.6,
    #                    13.48,
    #                    1.3,
    #                    0.24,
    #                    0.81]

class Migration(migrations.Migration):

    dependencies = [
        ('suffi', '0011_auto_20190824_2058'),
    ]

    operations = [
        migrations.RunPython(init_data),
    ]
