# Generated by Django 2.2.4 on 2019-08-24 19:19

from django.db import migrations
from suffi.greenAPI.models import Category, Challenge, Option, Trophy
from django.contrib.auth.models import User
import pandas as pd

def init_data(apps, schema_editor):
    # init Category table
    PATH = "data/initData.csv"
    df = pd.read_csv(PATH)

    cat_labels = ["Lebensmittel", "Verkehr", "Wohnen", "Kleider und Schuhe"]
    cat_icons = ["utensils", "car", "home", "tshirt"]
    for cat_label, cat_icon in zip(cat_labels, cat_icons):
        help = "Very useful information about " + cat_label
        cat = Category(icon=cat_icon, label=cat_label, help=help)
        cat.save()
        # init Challange table
        for idx, row in df.loc[df.category==cat_label].drop_duplicates('label').iterrows():
            info = "The " + row.label + " challenge is a very good challenge!"
            challange = Challenge(icon=row.icon,
                                  label=row.label,
                                  info=info,
                                  max_impact=row.max_impact,
                                  question=row.question,
                                  category=cat)
            challange.save()
            trophy = Trophy(icon=row.icon, label=row.trophy_label, challenge=challange)
            trophy.save()
            if not pd.isnull(row.option_title):
                for idx, option_row in df.loc[df.label==row.label].iterrows():
                    option = Option(title=option_row.option_title, co2=option_row.option_co2, challenge=challange)
                    option.save()
    newUser = User(username="Mr_Green",
                        email="mrgreen@suffi.ch")
    newUser.save()


class Migration(migrations.Migration):

    dependencies = [
        ('suffi', '0011_auto_20190824_2058'),
    ]

    operations = [
        migrations.RunPython(init_data),
    ]
