# Generated by Django 2.2.4 on 2019-08-25 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suffi', '0012_init_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activechallenge',
            old_name='challangeComplete',
            new_name='challengeComplete',
        ),
    ]
